name: "Build and Deploy"

on:
  push:
    branches:
      - steeltoe
    paths-ignore:
      - '**/*.md'
      - '**/*.gitignore'
      - '**/*.gitattributes'

env:
  AZURE_WEBAPP_NAME: aspnet-core-sample-deploy  # set this to your application's name
  AZURE_WEBAPP_PACKAGE_PATH_PLANET: './published_planet'      # set this to the path to your web app project, defaults to the repository root
  AZURE_WEBAPP_PACKAGE_PATH_SOLAR: './published_solar'      # set this to the path to your web app project, defaults to the repository root
  NETCORE_VERSION: '3.1.x'                      # set this to the .NET Core version to use
  SERVICE_RESOURCE_GROUP: SteeltoeRG
  SPRING_CLOUD_SERVICE_NAME: steeltoeservice

jobs:
  build:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Setup .NET Core SDK ${{ env.NETCORE_VERSION }}
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.NETCORE_VERSION }}

    - name: Login to Azure
      uses: azure/login@v1.1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Restore packages PLANET
      working-directory: steeltoe-sample/src/planet-weather-provider
      run: dotnet restore

    - name: Build app PLANET
      working-directory: steeltoe-sample/src/planet-weather-provider
      run: dotnet build --configuration Release --no-restore

    - name: Publish PLANET for deploy
      working-directory: steeltoe-sample/src/planet-weather-provider
      run: dotnet publish --configuration Release --no-build 

    - name: Deploy PLANET
      uses: azure/CLI@v1
      with:
        inlineScript: |
          az extension add --name spring-cloud
          az spring-cloud app deploy -g ${{ env.SERVICE_RESOURCE_GROUP }} -s ${{ env.SPRING_CLOUD_SERVICE_NAME }} -n planet-weather-provider --runtime-version NetCore_31 --main-entry Microsoft.Azure.SpringCloud.Sample.PlanetWeatherProvider.dll --artifact-path publish-deploy-planet.zip

    - name: Restore packages SOLAR
      working-directory: steeltoe-sample/src/solar-system-weather
      run: dotnet restore

    - name: Build app SOLAR
      working-directory: steeltoe-sample/src/solar-system-weather
      run: dotnet build --configuration Release --no-restore

    - name: Publish SOLAR for deploy
      working-directory: steeltoe-sample/src/solar-system-weather
      run: dotnet publish --configuration Release --no-build 

    - name: Deploy SOLAR
      uses: azure/CLI@v1
      with:
        inlineScript: |
          az extension add --name spring-cloud
          az spring-cloud app deploy -g ${{ env.SERVICE_RESOURCE_GROUP }} -s ${{ env.SPRING_CLOUD_SERVICE_NAME }} -n solar-system-weather --runtime-version NetCore_31 --main-entry Microsoft.Azure.SpringCloud.Sample.SolarSystemWeather.dll --artifact-path publish-deploy-solar.zip

    - name: Make public endpoint
      uses: azure/CLI@v1
      with:
        inlineScript: |
          az extension add --name spring-cloud
          az spring-cloud app update -g ${{ env.SERVICE_RESOURCE_GROUP }} -s ${{ env.SPRING_CLOUD_SERVICE_NAME }} -n solar-system-weather --is-public true