name: "Build and Deploy"

on:
  push:
    branches:
      - steeltoe
    paths-ignore:
      - '**/*.md'
      - '**/*.gitignore'
      - '**/*.gitattributes'
  workflow_dispatch:
    branches:
      - steeltoe

env:
  NETCORE_VERSION: '3.1.x'                      # set this to the .NET Core version to use
  SERVICE_RESOURCE_GROUP: SteeltoeRG
  SPRING_CLOUD_SERVICE_NAME: steeltoeservice
  PLANET_SERVICE_ROOT: steeltoe-sample/src/planet-weather-provider
  SOLAR_SERVICE_ROOT: steeltoe-sample/src/solar-system-weather
  FRONTEND_APP_ROOT: steeltoe-sample/src/frontend
  EXTENSION_SOURCE: https://steeltoe.blob.core.windows.net/cli/spring_cloud-0.5.1-py2.py3-none-any.whl

jobs:
  build:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Setup .NET Core SDK ${{ env.NETCORE_VERSION }}
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.NETCORE_VERSION }}

    - name: Login to Azure
      uses: azure/login@v1.1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Set resource defaults
      run: |
          az extension add --source ${{ env. EXTENSION_SOURCE }} -y
          az configure --defaults group=${{ env.SERVICE_RESOURCE_GROUP }}
          az configure --defaults spring-cloud=${{ env.SPRING_CLOUD_SERVICE_NAME }}

    - name: Restore packages PLANET
      working-directory: ${{ env.PLANET_SERVICE_ROOT }}
      run: dotnet restore

    - name: Build app PLANET
      working-directory: ${{ env.PLANET_SERVICE_ROOT }}
      run: dotnet build --configuration Release --no-restore

    - name: Publish PLANET for deploy
      working-directory: ${{ env.PLANET_SERVICE_ROOT }}
      run: dotnet publish --configuration Release --no-build 

    - name: Deploy PLANET
      run: |
          az spring-cloud app deploy -n planet-weather-provider --runtime-version NetCore_31 --main-entry Microsoft.Azure.SpringCloud.Sample.PlanetWeatherProvider.dll --artifact-path ${{ env.PLANET_SERVICE_ROOT }}/publish-deploy-planet.zip

    - name: Restore packages SOLAR
      working-directory: ${{ env.SOLAR_SERVICE_ROOT }}
      run: dotnet restore

    - name: Build app SOLAR
      working-directory: ${{ env.SOLAR_SERVICE_ROOT }}
      run: dotnet build --configuration Release --no-restore

    - name: Publish SOLAR for deploy
      working-directory: ${{ env.SOLAR_SERVICE_ROOT }}
      run: dotnet publish --configuration Release --no-build 

    - name: Deploy SOLAR
      run: |
          az spring-cloud app deploy -n solar-system-weather --runtime-version NetCore_31 --main-entry Microsoft.Azure.SpringCloud.Sample.SolarSystemWeather.dll --artifact-path ${{env.SOLAR_SERVICE_ROOT}}/publish-deploy-solar.zip

    - name: Restore packages FRONTEND
      working-directory: ${{ env.FRONTEND_APP_ROOT }}
      run: dotnet restore

    - name: Build app FRONTEND
      working-directory: ${{ env.FRONTEND_APP_ROOT }}
      run: dotnet build --configuration Release --no-restore

    - name: Publish FRONTEND for deploy
      working-directory: ${{ env.FRONTEND_APP_ROOT }}
      run: dotnet publish --configuration Release --no-build 

    - name: Deploy FRONTEND
      run: |
          az spring-cloud app deploy -n frontend-app --runtime-version NetCore_31 --main-entry frontend.dll --artifact-path ${{ env.FRONTEND_APP_ROOT }}/publish-deploy-frontend.zip --verbose

    - name: Make app public endpoint
      run: |
          az spring-cloud app update -n frontend-app --is-public true

    - name: Show app endpoint
      run: |
          az spring-cloud app show -n frontend-app -o table